#!/usr/bin/env python

import uuid, sys, os, random, datetime
import logging
logging.basicConfig()
import ConfigParser
sys.path.append(os.path.dirname(os.getcwd()))
from pssolib.types import *
from pssolib.utils import *
import uuid, sys, time, timeit
from multiprocessing import Process
import kazoo
from kazoo.client import KazooClient
from kazoo.exceptions import NodeExistsError
from kazoo.exceptions import BadVersionError
from kazoo.exceptions import ConnectionLoss

if len(sys.argv) != 7:
    print "Usage: {0} <P|Z> <spin|cas> <host1:port1>,<host2:port2>,...  <objectid> <#it> <nap>".format(sys.argv[0])
    sys.exit(1)

it=int(sys.argv[5])
nap=int(sys.argv[6])
A=0
B=10
    
#PSSOLib stuff

def pssolib_measure(obj,it):

    for k in range(0,it):

        if nap == 0:
            sleeptime = 0
        else:
            sleeptime = random.expovariate(1.0/nap)
        time.sleep(sleeptime*0.001)
        # print "Sleeping "+ str(sleeptime)+" ms"

        if obj == 'spin':
            executetime = timeit.timeit(spin_pssolib_access,number=1)*1000
        if obj == 'cas':
            executetime = timeit.timeit(cas_pssolib_access,number=1)*1000
        if obj == 'cons':
            executetime = timeit.timeit(cons_pssolib_access,number=1)*1000

        print "PID:"+str(get_thread_ident())+"\t"+str(executetime)

def spin_pssolib_access():
    try:
        spin.lock()
        print  str(datetime.datetime.utcnow().strftime('%Y%m%d%H%M%S%f')) +" "+str(get_thread_ident())+" LOCKED"
        spin.unlock()
        print  str(datetime.datetime.utcnow().strftime('%Y%m%d%H%M%S%f')) +" "+str(get_thread_ident())+" UNLOCKED"
    except:
        pass


def cas_pssolib_access():
    a = str(random.randint(A, B))
    b = str(random.randint(A, B))
    r = cas.compareandswap(a,b)
    # print  str(datetime.datetime.utcnow().strftime('%Y%m%d%H%M%S%f')) +" "+str(get_thread_ident())+" "+str(r)+" "+str(a)+" "+str(b)

def cons_pssolib_access():
    r = cons.propose(str(get_thread_ident()))

# ZK stuff

def zk_measure(obj,it):
    for k in range(0,it):

        if nap == 0:
            sleeptime = 0
        else:
            sleeptime = random.expovariate(1.0/nap)
        time.sleep(sleeptime*0.001)
        print "Sleeping "+ str(sleeptime)+" ms"

        if obj == 'spin':
            executetime = timeit.timeit(spin_zk_access,number=1)*1000
        if obj == 'cas':
            executetime = timeit.timeit(cas_zk_access,number=1)*1000

        print "PID:"+str(get_thread_ident())+"\t"+str(executetime)

def spin_zk_access():
    lock.acquire()
    print  str(datetime.datetime.utcnow().strftime('%Y%m%d%H%M%S%f')) +" "+str(get_thread_ident())+" LOCKED"
    lock.release()
    print  str(datetime.datetime.utcnow().strftime('%Y%m%d%H%M%S%f')) +" "+str(get_thread_ident())+" UNLOCKED"

def cas_zk_access():
    a = str(random.randint(A, B))
    b = str(random.randint(A, B))
    r = cas_zk(a,b)
    print  str(datetime.datetime.utcnow().strftime('%Y%m%d%H%M%S%f')) +" "+str(get_thread_ident())+" "+str(r)+" "+str(a)+" "+str(b)

# This is not wait-free
def cas_zk(a,b):
    retry = True
    while retry == True:
        t = zk.get(cas)
        if t[0] == a:
            try:
                zk.set(cas,b,(t[1].version))
                return True
            except BadVersionError:
                pass
        else:
            retry = False
    return False

# Configuration & Evaluation

if sys.argv[1]=="P":

    parser = ConfigParser.ConfigParser()
    parser.add_section("main")
    parser.set("main","servers",sys.argv[3])
    parser.set("main","keyspace","access")
    cfg = Config.create(parser,False)

    id1=uuid.UUID(sys.argv[4])
    if sys.argv[2] == 'spin':
        spin = Spinlock(id1)
    else:
        cas = Cas(id1,str(0))
    pssolib_measure(sys.argv[2],it)

else:

    zk = KazooClient(hosts=sys.argv[3])    
    isConnected=False
    while isConnected == False:
        try:
            zk.start()
            isConnected = True
        except:
            pass

    if sys.argv[2] == 'spin':
        lock = zk.Lock("/"+sys.argv[4])
    else:
        cas = "/"+sys.argv[4]
        try:
            zk.create(cas,str(0))
        except:
            pass

    zk_measure(sys.argv[2],it)
    zk.stop()


# Closing stdout/err

try:
    sys.stdout.close()
except:
    pass
try:
    sys.stderr.close()
except:
    pass
