#!/bin/sh
grep -H "(True)" /tmp/exp/* | awk '{print $3" "$4" "$5}' | sort -V \
    | awk ' \
      BEGIN{LAST=0} \
      { \
       if (LAST != $2) { \
         print $0 \
       } \
       LAST = $3 \
      }'
